### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by nikolay** [pior/caravan#4]
It's sad to see this is not being compatible with Python 3 mainly because of print statements.

**Comment by pior** [comment]
@nikolay I'm using Python 2.7 only at work, and didn't finish to write the tests*. That's why it's (stupidely) not Python 3 compatible.

However, I'll setup the tests to run on 3.3/3.4/3.5 this week.
-  (actually got annoyed by pytest, reverting to Nose)

**Comment by nikolay** [comment]
Big thanks in advance, @pior!

**Comment by pior** [comment]
Release 0.2.0 is tested with python 3.x. https://pypi.python.org/pypi/caravan

However the coverage is poor at this time... I will work faster on it now.

 @nikolay, any feedback on Python 3 is welcome!

**Comment by nikolay** [comment]
@pior Thank you very much! You definitely beat all my expectations! I will test and provide feedback. Great job!
